
services:
  - type: web
    name: fb-token-extractor
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    autoDeploy: true
